#!/bin/sh

# This is also a standalone scriptlet which restores the grub config file.
# So option handler is at the end of file.
GRUB_MENU_FILE="/boot/grub/grub.conf"

ChangeGrubMenu() {
    if [ x"$CHANGE_GRUB_MENU" = "x1" ] ; then
	vecho 2 "Changing grub menu ..."
	if [ -f $GRUB_MENU_FILE ] ;then
	    # given file exists so change menu
	    cp -R "$GRUB_MENU_FILE" "$GRUB_MENU_FILE.suspend.sh_bak"
	    echo  >> "$GRUB_MENU_FILE"
	    echo "title ______________________________________________" >> "$GRUB_MENU_FILE"
	    echo "configfile dummy" >> "$GRUB_MENU_FILE"
	    echo "title WARNING: "`uname -s -r` "is suspended via swsusp!" >> "$GRUB_MENU_FILE"
	    echo "configfile dummy" >> "$GRUB_MENU_FILE"
	    # Call sync to ensure it is written to disk (do we still need double/triple syncs?)
	    sync ; sync
	fi
    fi
}

RestoreGrubMenu() {
    if [ x"$CHANGE_GRUB_MENU" = "x1" ] ; then
	vecho 2 "Restoring grub menu."
	if [ -f $GRUB_MENU_FILE.suspend.sh_bak ] ;then
	    mv -f "$GRUB_MENU_FILE.suspend.sh_bak" "$GRUB_MENU_FILE"
	fi
    fi
}

GrubConfigOptions() {
    case $1 in
	changegrubmenu)
	    BoolIsOn "$1" "$2" && CHANGE_GRUB_MENU=1 || return 0
	    ;;
	grubmenufile)
	    GRUB_MENU_FILE="$2"
	    return 0
	    ;;
	*)
	    return 1
    esac
    if [ -z "$GRUB_HOOKED" ] ; then
	AddSuspendHook 11 ChangeGrubMenu
	AddResumeHook 11 RestoreGrubMenu
	GRUB_HOOKED=1
    fi
    return 0
}

GrubCmdlineOptions() {
    case $1 in
	-g|--restore-grub)
	    if [ -x "$SCRIPTLET_DIR/grub" ] ; then
		$SCRIPTLET_DIR/grub
		exit 0
	    fi

	    echo "Grub script not found :("
	    exit 1
	    ;;
	*)
	    return 1
    esac
    return 0
}


## Main for standalone ##
if [ "`basename $0`" = "grub" ] ; then
    vecho() { # Define a vecho
	shift
	echo $*
    }

    ## look at /etc/suspend/suspend.conf for GrubMenuFile
    while read option param ; do
	[ "`echo $option | tr '[A-Z]' '[a-z]'`" = "grubmenufile" ] || continue
	GRUB_MENU_FILE=$param
	break
    done < /etc/suspend/suspend.conf

    # we want to restore always
    CHANGE_GRUB_MENU=1

    # restore grub and exit
    RestoreGrubMenu
    exit 0
else
    ## called as part of suspend.sh 
    AddConfigHandler GrubConfigOptions
    AddConfigHelp "ChangeGrubMenu <boolean>" "Change grub's config file to show system is suspended before suspending and restore after resume."
    AddConfigHelp "GrubMenuFile <filename>" "Filename of grub's config file. Default is /boot/grub/grub.conf."

    AddOptionHandler GrubCmdlineOptions
    AddShortOption 'g'
    AddLongOption 'restore-grub'
    AddOptionHelp '-g, --restore-grub' 'Restores the grub menu to normal (use if a suspend was not completed sucessfully) and exits the script. Does not hibernate.'
fi

# $Id$
# vim:ft=sh:ts=8:sw=4:noet
