#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 <version number>" && exit

FULLNAME=suspend2-userui-$1

[ -e $FULLNAME -o -e $FULLNAME.tar.gz ] && echo "Already exists!" && exit

! cp -a tags/release-$1 $FULLNAME && echo "No such release?" && exit 1
fakeroot tar --exclude '.svn' --exclude 'fbanim' --exclude 'themes' -czvf $FULLNAME.tar.gz $FULLNAME
rm -rf "$FULLNAME"
